# Site wide configuration

title: "Jonathan Duck"
description: "Web Development"
#if you modify locale please have a look at _data/messages.yml too
locale: en
#for meta name="author" :
author: 

# Site owner
owner:
  name: Jonathan Duck
  email: duckbrain30@gmail.com
  twitter:
  google-plus:
  instagramm:
  #Aboutlink = German "Impressum", provide url and caption (eg "Impressum")
  aboutlink:
    url:
    caption:


# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
kramdown:
  toc_levels: 1..2
  
permalink: /blog/:year/:month/:day/:title


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
